# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty32"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "public_network"
  # config.vm.synced_folder "../SVN", "/svn"

  # allow SSH connections via port 2223
  config.vm.network "forwarded_port", guest: 22, host: 2223

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end

  # call shell script with optional argument containing location of DB2 source, otherwise this will be downloaded
  config.vm.provision "shell", path: "bootstrap.sh", privileged: false, args: "'/vagrant/db2/v10.5fp7_linuxia32_server_t.tar.gz'"

end
